include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error rules
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    valid_regexps: true

    # Style rules
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_return_types_on_setters: true
    await_only_futures: true
    camel_case_types: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_single_quotes: true
    unnecessary_brace_in_string_interps: true
    use_rethrow_when_possible: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
